# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


def hash_ip(apps, schema_editor):
    from djangoratings.fields import md5_hexdigest
    Vote = apps.get_model('djangoratings.Vote')
    for item in Vote.objects.all().iterator():
        if not item.ip_address:
            continue
        item.hashed_ip_address = md5_hexdigest(item.ip_address)
        item.save(update_fields=['hashed_ip_address'])


def blank_ip(apps, schema_editor):
    Vote = apps.get_model('djangoratings.Vote')
    Vote.objects.update(ip_address=None)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='hashed_ip_address',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.RunPython(hash_ip),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('content_type', 'object_id', 'key', 'user', 'hashed_ip_address', 'cookie')]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.RunPython(blank_ip),
    ]
