# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='hashed_ip_address',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('content_type', 'object_id', 'key', 'user', 'hashed_ip_address', 'cookie')]),
        ),
    ]
